### ISSUE TITLE
Error: Scene modified within a rendering callback of another scene

### ISSUE THREAD

**Issue by buabbud** [google-ar/arcore-ios-sdk#17] opened 2018-11-12 01:54 UTC
Hello,

I'm running an unaltered build and I get the following error upon hosting an anchor:

`CloudAnchorExampleSwift[4851:792109] [SceneKit] Error: Scene <SCNScene: 0x284dc0280> is modified within a rendering callback of another scene (<SCNScene: 0x280ae5680>). This is not allowed and may lead to crash`

Would you be able to help me find a workaround for this? Any help would be appreciated.

**Comment by sammcd** [comment] 2019-02-11 17:19
Apologies for the very late response.

We don't currently have a Swift version of our cloud anchor example. Could you point me towards the code you are running so I might be able to see what the problem is?

Thanks!

**Comment by sammcd** [comment] 2019-02-18 20:36
Closing this, but feel free to reopen if there is any way for me to help out.

**Closed by sammcd** 2019-02-18 20:36 UTC
